name: KMM Workshop
options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
settings:
  PRODUCT_BUNDLE_IDENTIFIER: "io.shortcut.ios"
  MARKETING_VERSION: 0.0.1
  CURRENT_PROJECT_VERSION: 1
configs:
  Debug: debug
  integ: debug
  test: debug
  Release: release
targets:
  "KMM Workshop":
    type: application
    platform: iOS
    deploymentTarget: "13.2"
    sources:  
      - path: "KMM Workshop"
    scheme: 
      testTargets:
        - "KMM Workshop Tests"
        - "KMM Workshop UITests"
      gatherCoverageData: true
  "KMM Workshop Tests":
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.2"
    sources:
      - path: "KMM Workshop Tests"
    dependencies:
      - target: "KMM Workshop"
    scheme: 
      testTargets:
        - "KMM Workshop"
        - "KMM Workshop Tests"
      gatherCoverageData: true
  "KMM Workshop UITests":
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: "KMM Workshop UITests"
    dependencies:
      - target: "KMM Workshop"